version: "3.9"

services:
  # Defining app image
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: chanel-app
    # Command to run the api
    command: uvicorn app.main:app --host 0.0.0.0 --port 80 --reload
    # Environment variables
    environment:
      # By default in postgres image the user ir "postgres"
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=my_password
      - POSTGRES_PORT=5432
      # By default in postgres image the initial db is named as the user "postgres"
      - POSTGRES_DB_NAME=postgres
      # db solves the problem of connectivity after trying with "postgres" and "localhost"
      - POSTGRES_HOST=db
    ports:
      #port on machine:port on container
      - 8080:80
    volumes:
      - ./app:/app
      - ./docs/networks:/networks
      - ./docs/fortran:/fortran
    depends_on:
      - db

  # Defining the database image
  db:
    image: postgres
    restart: always

    # Environment variables
    environment:
      # Password is the only env variable required
      POSTGRES_PASSWORD: my_password
      # POSTGRES_USER: 
      # POSTGRES_DB: default(POSTGRES_USER)
    ports:
      #port on machine:port on container
      - 5432:5432
    container_name: chanel-postgres-db
    volumes:
      #path on my mac machine:path to postgres default folder
      - postgres-data:/var/lib/postgresql/data
    privileged: true

volumes:
  postgres-data:
