# Python version
FROM python:3.11.4

# Install app requirements
COPY requirements/app.txt .
RUN pip install -r app.txt

# Install `fortran`
RUN apt-get update
RUN	echo Y | apt-get install gfortran

# Build file system
COPY ./app ./app
RUN python app/config/file_config.py
