version: "3.9"

services:
  # Defining app image
  app_test:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: chanel-app-test
    # Command to run the api
    command: pytest tests 

    # Environment variables
    environment:
      # By default in postgres image the user ir "postgres"
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=my_password
      - POSTGRES_PORT=5432
      # By default in postgres image the initial db is named as the user "postgres"
      - POSTGRES_DB_NAME=postgres
      # db solves the problem of connectivity after trying with "postgres" and "localhost"
      - POSTGRES_HOST=postgres-db-tests
    volumes:
      - ./app:/app
      - ./tests:/tests

    depends_on:
      - postgres-db-tests

  # Defining the database image
  postgres-db-tests:
    image: postgres
    restart: always

    # Environment variables
    environment:
      # Password is the only env variable required
      POSTGRES_PASSWORD: my_password
      # POSTGRES_USER: 
      # POSTGRES_DB: default(POSTGRES_USER)
    ports:
      #port on machine:port on container
      - 6432:5432
    container_name: chanel-postgres-db-tests
    privileged: true


  
