# Python version
FROM python:3.11.4

# Install app requirements
ADD ./requirements/app.txt app.txt
ADD ./requirements/tests.txt tests.txt
RUN pip install -r app.txt -r tests.txt

# Install `fortran`
RUN apt-get update
RUN	echo Y | apt-get install gfortran

# Build file system
ADD ./app ./app
RUN python app/config/file_config.py

# Copy the network file to test
ADD ./NetworkFiles/UniformNetwork.txt UniformNetwork.txt