version: "3.9"

services:
  # Defining app image
  app:
    build:
      # Since the default file name should be Dockerfile, this line of code is essential
      context: .
      dockerfile: Dockerfile.dev
    # Setting the volum to share app code with the host machine
    volumes:
      - .:/app
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db
    ## Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    ## (Adding the "ports" property to this file will not forward from a Codespace.)
    # Setting environtment varibles to connect the app with the database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=my_password
      - POSTGRES_PORT=5432
      - POSTGRES_DB_NAME=postgres
      - POSTGRES_HOSTNAME=localhost
    # Don't actually know why thats in here
    depends_on:
      - db

  # Defining the database image
  db:
    image: postgres
    restart: always

    # Environment variables
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: my_password
      ##POSTGRES_HOST_AUTH_METHOD: trust
      ##POSTGRES_HOST: postgres
      ##PGDATA: d:/pg #/var/lib/postgresql/data/pgdata
    ports:
      #port on machine:port on container
      - 1234:5432
    volumes:
      #path on my windows machine:path to postgres default folder
      - postgres-data:/var/lib/postgresql/data
    privileged: true

volumes:
  postgres-data:


