version: "3.9"

services:
  # Defining app test image
  app-test:
    container_name: channel-app-test
    build:
      context: .
      dockerfile: docker/test/python/Dockerfile
    # Path to envionment variables to store int the container
    env_file:
      - .envs/.test/postgres.env
      - .envs/.test/minio.env
    ports:
      - 9080:80
    depends_on:
      - postgres
      - minio
    # Command to run the api
    command: pytest 

  # Defining the postgres database image for testing
  postgres:
    container_name: channel-postgres-test
    build:
      context: .
      dockerfile: docker/develop/postgres/Dockerfile
    ports:
      - 6432:5432
    restart: always
    privileged: true

  minio:
    container_name: channel-minio-test
    image: minio/minio
    restart: always
    ports:
      - 9001:9000
    environment:
      - MINIO_ROOT_USER=myrootuser
      - MINIO_ROOT_PASSWORD=myrootpassword

    command: server /data